<a href="https://colab.research.google.com/github/Pritush09/DeepLearning-Pytorch/blob/master/00_Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi 
# for lookin the gpu type which we are alloted

/bin/bash: nvidia-smi: command not found


#CUDA® is a parallel computing platform and programming model developed by NVIDIA for general computing on graphical processing units (GPUs)

In [3]:
import torch
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
print(torch.__version__)

2.0.0+cu118


## Introduction To **tensors**

torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy.
 If you have a numpy array and want to avoid a copy, use torch.as_tensor().

Random sampling creation ops are listed under Random sampling and include: 
torch.rand() torch.rand_like() torch.randn() torch.randn_like() torch.randint() torch.randint_like() torch.randperm() You may also use torch.empty() with the In-place random sampling methods to create torch.
Tensor s with values sampled from a broader range of distributions.

tensors aare created using `torch.tensor()` link = https://pytorch.org/docs/stable/tensors.html

In [5]:
#creating a scalars
scalar = torch.tensor(120)
scalar

tensor(120)

In [6]:
scalar.ndim #Scalar doesnt have dimensions

0

In [7]:
# get tensor back as python int
type(scalar.item())

int

In [8]:
#vector 
vector = torch.tensor([2,3])
v1 = torch.tensor([[1,2]])
vector

tensor([2, 3])

In [9]:
print(vector.ndim)
print(v1.ndim)

1
2


In [10]:
vector.shape

torch.Size([2])

In [11]:
v1.shape

torch.Size([1, 2])

In [12]:
# MATRIX 
matrix =  torch.tensor([[1,1],[2,2]])
matrix.shape

torch.Size([2, 2])

In [13]:
matrix.ndim

2

In [14]:
matrix[0]

tensor([1, 1])

In [15]:
# TENSORS 
tsnr = torch.tensor([[[[1,1,1,1],
                      [1,2,3,4],
                      [1,1,2,2]]],
                     [[[1,1,1,1],
                       [2,2,2,2],
                       [3,3,3,3]]]])

In [16]:
tsnr.shape

torch.Size([2, 1, 3, 4])

# Note: we use upper case letter to represent matix and lower case letter to represent a scaler and a array 

### Random Tensors
it is important because the NN start with  random numbers as their weight and bias and then adjust it according to there leaaning to get  a good reuslt 

`start with random numbers -> look at the data  -> update random number 
to represent the data in best way`

`torch.rand` https://pytorch.org/docs/stable/generated/torch.randn.html

In [17]:
# Random tensors 
random_tensor = torch.rand(3,4)

In [18]:
random_tensor

tensor([[0.4015, 0.0267, 0.2762, 0.6695],
        [0.3921, 0.3644, 0.6292, 0.2077],
        [0.0580, 0.8229, 0.6532, 0.6122]])

In [19]:
random_tensor.ndim

2

In [20]:
# creating image with the tensors 
# in the format height , width , colorchannel(RGB)
img = torch.rand(size=(224,224,3))
img

tensor([[[2.2985e-01, 4.5012e-01, 8.7875e-01],
         [9.7495e-01, 6.6532e-01, 2.8360e-01],
         [8.2554e-01, 5.4710e-01, 1.5084e-01],
         ...,
         [2.7804e-02, 8.0982e-02, 9.1188e-01],
         [2.3079e-01, 8.1021e-01, 8.1227e-02],
         [1.9975e-01, 6.4651e-01, 7.6088e-01]],

        [[4.3807e-01, 3.0884e-01, 8.6672e-02],
         [3.6769e-01, 6.8768e-03, 5.1992e-01],
         [1.5357e-01, 2.6878e-01, 9.5548e-01],
         ...,
         [4.8580e-01, 9.3764e-01, 7.8882e-01],
         [2.5198e-02, 8.4792e-01, 5.6163e-01],
         [7.1541e-01, 5.8122e-01, 5.5438e-03]],

        [[5.2586e-01, 5.6842e-01, 1.8437e-01],
         [1.1209e-01, 2.0607e-01, 9.6222e-01],
         [9.5697e-01, 4.6556e-01, 2.9949e-01],
         ...,
         [3.4302e-01, 4.6415e-01, 5.1778e-01],
         [4.2265e-02, 3.1720e-01, 8.1672e-01],
         [6.7837e-01, 5.5497e-01, 6.2730e-01]],

        ...,

        [[4.3307e-01, 9.5347e-02, 9.5414e-02],
         [8.6737e-01, 2.3257e-01, 4.0838e-01]

In [21]:
img = torch.rand(size=(3,224,224))
img
# ths is correct for sure

tensor([[[0.6275, 0.1064, 0.0251,  ..., 0.5044, 0.9751, 0.0907],
         [0.5528, 0.3033, 0.5539,  ..., 0.0502, 0.3407, 0.7710],
         [0.6417, 0.3788, 0.7076,  ..., 0.2403, 0.1265, 0.9954],
         ...,
         [0.0966, 0.7475, 0.5055,  ..., 0.2182, 0.6347, 0.6316],
         [0.3821, 0.8310, 0.2617,  ..., 0.5294, 0.5085, 0.4777],
         [0.9584, 0.2196, 0.7043,  ..., 0.5127, 0.1408, 0.2117]],

        [[0.0534, 0.7361, 0.7977,  ..., 0.0234, 0.3871, 0.0874],
         [0.3901, 0.3159, 0.7714,  ..., 0.6759, 0.5018, 0.5242],
         [0.4652, 0.4409, 0.0394,  ..., 0.9812, 0.6453, 0.8013],
         ...,
         [0.0244, 0.5857, 0.5883,  ..., 0.5202, 0.4502, 0.9207],
         [0.7200, 0.7839, 0.3863,  ..., 0.2391, 0.4953, 0.4882],
         [0.8838, 0.4790, 0.9945,  ..., 0.7397, 0.9438, 0.2788]],

        [[0.9829, 0.5143, 0.4581,  ..., 0.3139, 0.5140, 0.5585],
         [0.5272, 0.7985, 0.1375,  ..., 0.8943, 0.4575, 0.9700],
         [0.7902, 0.7613, 0.9701,  ..., 0.4195, 0.1494, 0.

# zeros and ones


In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)


Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1).

Note: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.

In [24]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-24-a09072c806d9>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use `torch.zeros_like(input)` or `torch.ones_like(input)` which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [25]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes
There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which is which can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

Resources:

See the PyTorch documentation for a list of all available tensor datatypes.
Read the Wikipedia page for an overview of what precision in computing is.
Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter.

In [26]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

In [27]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16


Getting information from tensors
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)

dtype - what datatype are the elements within the tensor stored in?

device - what device is the tensor stored on? (usually GPU or CPU)

In [28]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2198, 0.6540, 0.9845, 0.9354],
        [0.1174, 0.0726, 0.1602, 0.4232],
        [0.6199, 0.1462, 0.8228, 0.6416]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Note: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":

"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"


# Manipulating tensors (tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

Addition
Substraction
Multiplication (element-wise)
Division
Matrix multiplication
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

Basic operations
Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

They work just as you think they would.

In [29]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])


Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned.

In [31]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [32]:
tensor = tensor+10
tensor

tensor([1, 2, 3])

PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplcation) and torch.add() to perform basic operations.

In [33]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [34]:
tensor

tensor([1, 2, 3])

In [35]:
# BUt in usecase the symbols are more used 
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])



# Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

In [36]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

he difference between element-wise multiplication and matrix multiplication is the addition of values.

For our tensor variable with values [1, 2, 3]:

     Operation  	                     Calculation	               Code

    Element-wise multiplication    [1*1, 2*2, 3*3] = [1, 4, 9]	  tensor * tensor
    Matrix multiplication	       [1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

In [37]:
tensor * tensor

tensor([1, 4, 9])

In [38]:
# Matrix multiplication
tensor.matmul(tensor)

tensor(14)

In [39]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)


You can do matrix multiplication by hand but it's not recommended.

The in-built torch.matmul() method is faster.

In [40]:
len(tensor)

3

In [41]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 225 µs, sys: 40 µs, total: 265 µs
Wall time: 270 µs


tensor(14)

In [42]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 106 µs, sys: 0 ns, total: 106 µs
Wall time: 111 µs


tensor(14)


# One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [43]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B)     # (this will error)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
tensor.T - where tensor is the desired tensor to transpose.

In [44]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [45]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [46]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [47]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

we can create animation on this this multiplication ussing http://matrixmultiplication.xyz/
 
dot product of two matrices.

Neural networks are full of matrix multiplications and dot products.
The torch.nn.Linear() module also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

y
=
x
⋅
A
T
+
b

Where:

x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).

A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).

Note: You might also often see W or another letter like X used to showcase the weights matrix.

b is the bias term used to slightly offset the weights and inputs.

y is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function and can be used to draw a straight line!

In [48]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [49]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=1, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

# the error explains it all what is happening

RuntimeError: ignored

In [50]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


Finding the min, max, mean, sum, etc (aggregation)
Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.

In [51]:
x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 9
Mean: 4.5
Sum: 45


# Note: You may find some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.

In [53]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(9), tensor(0), tensor(4.5000), tensor(45))


# Positional min/max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).
https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html

In [54]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0



# Change tensor datatype
As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in torch.float64 and another is in torch.float32, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype you'd like to use.

First we'll create a tensor and check it's datatype (the default is torch.float32).

In [55]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [56]:
tensor = tensor.type(torch.float16)
tensor.dtype

torch.float16

Note: Different datatypes can be confusing to begin with. But think of it like this, the lower the number (e.g. 32, 16, 8), the less precise a computer stores the value. And with a lower amount of storage, this generally results in faster computation and a smaller overall model. Mobile-based neural networks often operate with 8-bit integers, smaller and faster to run but less accurate than their float32 counterparts. For more on this, I'd read up about precision in computing.

# Reshaping, stacking, squeezing and unsqueezing

In [57]:
# creating a matrix 
tensor = torch.arange(1,11)
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
tensor.shape,tensor.dtype

(torch.Size([10]), torch.int64)

In [59]:
tensor.reshape(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [60]:
tensor.shape
# it doesnt chages the real one shape

torch.Size([10])

In [61]:
# USing the view function
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723 
tensor.view(5,2) , tensor.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([10]))

In [62]:
z = tensor.view(5,2)
z , z.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

### Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

In [63]:
z[0,:] = 10
z , tensor

(tensor([[10, 10],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 tensor([10, 10,  3,  4,  5,  6,  7,  8,  9, 10]))

### Here we can see the same goes for the reshape method

In [64]:
reshaped  = tensor.reshape(2,5)
reshaped , reshaped.shape

(tensor([[10, 10,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [65]:
reshaped[0,0] = 1
reshaped[0,1] = 2
reshaped , tensor

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

# Stack

If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

dim (int) – dimension to insert. Has to be between 0 and the number of dimensions of concatenated tensors (inclusive)

In [66]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
# this is vertical 
x_stacked

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [67]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) 
# this is horizontal after transposing
x_stacked

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [68]:
x_stack = torch.stack([x,x,x,x],dim=-2)
x_stack

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [69]:
x_stack = torch.stack([x,x,x,x],dim=-1)
x_stack

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

# Squeezing
How about removing all single dimensions from a tensor?

To do so you can use torch.squeeze()

In [71]:
print(f"Previous tensor: \n{reshaped}")
print(f"Previous shape: {reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = reshaped.squeeze()
print(f"\nNew tensor: \n{x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: 
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
Previous shape: torch.Size([2, 5])

New tensor: 
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
New shape: torch.Size([2, 5])


##### # We can see this dont work on the 2d tensor

In [72]:
x = torch.arange(1,11)
print(f"Previous tensor: {x}")
x = x.reshape(1,10)
print(f"Previous shape: {x.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
New shape: torch.Size([10])



And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [73]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Previous shape: torch.Size([10])

New tensor: tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
New shape: torch.Size([1, 10])



You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [79]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))
# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")



torch.Size([224, 224, 3])


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [83]:
x_original[0].shape

torch.Size([224, 3])

`Note:` Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

# Indexing (selecting data from tensors)
Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

In [87]:
x = torch.arange(1, 19).reshape(2, 3, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [88]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1



You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.

In [90]:
x.shape

torch.Size([2, 3, 3])

In [94]:
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [93]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0, :3]

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [96]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1] ,  x[:, :, 1].shape

(tensor([[ 2,  5,  8],
         [11, 14, 17]]),
 torch.Size([2, 3]))

In [97]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([ 5, 14])

In [99]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :]  , x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

# PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [100]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

`Note:` By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).