<a href="https://colab.research.google.com/github/Pritush09/DeepLearning-Pytorch/blob/master/00_Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi 
# for lookin the gpu type which we are alloted

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



#CUDA® is a parallel computing platform and programming model developed by NVIDIA for general computing on graphical processing units (GPUs)

In [3]:
import torch
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
print(torch.__version__)

2.0.0+cu118


## Introduction To **tensors**

torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy.
 If you have a numpy array and want to avoid a copy, use torch.as_tensor().

Random sampling creation ops are listed under Random sampling and include: 
torch.rand() torch.rand_like() torch.randn() torch.randn_like() torch.randint() torch.randint_like() torch.randperm() You may also use torch.empty() with the In-place random sampling methods to create torch.
Tensor s with values sampled from a broader range of distributions.

tensors aare created using `torch.tensor()` link = https://pytorch.org/docs/stable/tensors.html

In [5]:
#creating a scalars
scalar = torch.tensor(120)
scalar

tensor(120)

In [6]:
scalar.ndim #Scalar doesnt have dimensions

0

In [7]:
# get tensor back as python int
type(scalar.item())

int

In [8]:
#vector 
vector = torch.tensor([2,3])
v1 = torch.tensor([[1,2]])
vector

tensor([2, 3])

In [9]:
print(vector.ndim)
print(v1.ndim)

1
2


In [10]:
vector.shape

torch.Size([2])

In [11]:
v1.shape

torch.Size([1, 2])

In [12]:
# MATRIX 
matrix =  torch.tensor([[1,1],[2,2]])
matrix.shape

torch.Size([2, 2])

In [13]:
matrix.ndim

2

In [14]:
matrix[0]

tensor([1, 1])

In [15]:
# TENSORS 
tsnr = torch.tensor([[[[1,1,1,1],
                      [1,2,3,4],
                      [1,1,2,2]]],
                     [[[1,1,1,1],
                       [2,2,2,2],
                       [3,3,3,3]]]])

In [16]:
tsnr.shape

torch.Size([2, 1, 3, 4])

# Note: we use upper case letter to represent matix and lower case letter to represent a scaler and a array 

### Random Tensors
it is important because the NN start with  random numbers as their weight and bias and then adjust it according to there leaaning to get  a good reuslt 

`start with random numbers -> look at the data  -> update random number 
to represent the data in best way`

`torch.rand` https://pytorch.org/docs/stable/generated/torch.randn.html

In [17]:
# Random tensors 
random_tensor = torch.rand(3,4)

In [18]:
random_tensor

tensor([[0.8869, 0.6390, 0.6448, 0.1471],
        [0.7156, 0.7161, 0.0756, 0.7444],
        [0.1627, 0.4358, 0.2576, 0.2631]])

In [19]:
random_tensor.ndim

2

In [20]:
# creating image with the tensors 
# in the format height , width , colorchannel(RGB)
img = torch.rand(size=(224,224,3))
img

tensor([[[0.3107, 0.1965, 0.1736],
         [0.6463, 0.9465, 0.3682],
         [0.1664, 0.0324, 0.5888],
         ...,
         [0.1325, 0.8100, 0.1705],
         [0.5075, 0.1324, 0.5537],
         [0.8781, 0.5574, 0.5481]],

        [[0.6740, 0.1434, 0.0108],
         [0.2889, 0.5369, 0.2508],
         [0.5047, 0.6475, 0.4796],
         ...,
         [0.6524, 0.5774, 0.0046],
         [0.1946, 0.6488, 0.2316],
         [0.0749, 0.1154, 0.7616]],

        [[0.0680, 0.3578, 0.0617],
         [0.6490, 0.6688, 0.4819],
         [0.6842, 0.3347, 0.2256],
         ...,
         [0.6686, 0.7645, 0.9912],
         [0.6000, 0.0444, 0.8978],
         [0.9593, 0.2340, 0.3963]],

        ...,

        [[0.4356, 0.8191, 0.1035],
         [0.1680, 0.3781, 0.1375],
         [0.4778, 0.4151, 0.0962],
         ...,
         [0.7495, 0.4238, 0.1273],
         [0.6378, 0.9939, 0.2206],
         [0.2354, 0.4151, 0.3542]],

        [[0.5813, 0.0636, 0.4712],
         [0.6373, 0.1113, 0.1629],
         [0.

In [21]:
img = torch.rand(size=(3,224,224))
img
# ths is correct for sure

tensor([[[0.4195, 0.8638, 0.9281,  ..., 0.6649, 0.6274, 0.4152],
         [0.6292, 0.5758, 0.1396,  ..., 0.6739, 0.9897, 0.4435],
         [0.6125, 0.2083, 0.2712,  ..., 0.1704, 0.3388, 0.0387],
         ...,
         [0.9260, 0.0810, 0.9525,  ..., 0.5141, 0.1295, 0.9480],
         [0.6717, 0.5511, 0.8154,  ..., 0.9528, 0.7581, 0.7263],
         [0.8360, 0.1731, 0.4790,  ..., 0.3743, 0.8541, 0.2799]],

        [[0.1903, 0.0468, 0.9882,  ..., 0.5916, 0.4495, 0.2412],
         [0.6294, 0.7804, 0.6986,  ..., 0.5421, 0.5763, 0.7707],
         [0.9848, 0.9678, 0.1302,  ..., 0.9358, 0.7397, 0.6473],
         ...,
         [0.4523, 0.8208, 0.0849,  ..., 0.4421, 0.6265, 0.7604],
         [0.1666, 0.8807, 0.6707,  ..., 0.6157, 0.0034, 0.7764],
         [0.5551, 0.6339, 0.6579,  ..., 0.6753, 0.2702, 0.1521]],

        [[0.2049, 0.1904, 0.5874,  ..., 0.8874, 0.7513, 0.4287],
         [0.4752, 0.4996, 0.7067,  ..., 0.0623, 0.8985, 0.4478],
         [0.1850, 0.5739, 0.1611,  ..., 0.6604, 0.5720, 0.

# zeros and ones


In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)


Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1).

Note: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.

In [24]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-24-a09072c806d9>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use `torch.zeros_like(input)` or `torch.ones_like(input)` which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [25]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes
There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which is which can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

Resources:

See the PyTorch documentation for a list of all available tensor datatypes.
Read the Wikipedia page for an overview of what precision in computing is.
Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter.

In [26]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

In [27]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16


Getting information from tensors
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)

dtype - what datatype are the elements within the tensor stored in?

device - what device is the tensor stored on? (usually GPU or CPU)

In [28]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2139, 0.8572, 0.2266, 0.1973],
        [0.4133, 0.5153, 0.1845, 0.6648],
        [0.5355, 0.0196, 0.3024, 0.7469]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Note: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":

"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"


# Manipulating tensors (tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

Addition
Substraction
Multiplication (element-wise)
Division
Matrix multiplication
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

Basic operations
Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

They work just as you think they would.

In [29]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])


Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned.

In [31]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [32]:
tensor = tensor+10
tensor

tensor([1, 2, 3])

PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplcation) and torch.add() to perform basic operations.

In [33]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [34]:
tensor

tensor([1, 2, 3])

In [35]:
# BUt in usecase the symbols are more used 
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])



# Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

In [36]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

he difference between element-wise multiplication and matrix multiplication is the addition of values.

For our tensor variable with values [1, 2, 3]:

     Operation  	                     Calculation	               Code

    Element-wise multiplication    [1*1, 2*2, 3*3] = [1, 4, 9]	  tensor * tensor
    Matrix multiplication	       [1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

In [37]:
tensor * tensor

tensor([1, 4, 9])

In [38]:
# Matrix multiplication
tensor.matmul(tensor)

tensor(14)

In [39]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)


You can do matrix multiplication by hand but it's not recommended.

The in-built torch.matmul() method is faster.

In [40]:
len(tensor)

3

In [41]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 273 µs, sys: 0 ns, total: 273 µs
Wall time: 282 µs


tensor(14)

In [42]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 97 µs, sys: 19 µs, total: 116 µs
Wall time: 123 µs


tensor(14)


# One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [44]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B)     # (this will error)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
tensor.T - where tensor is the desired tensor to transpose.

In [45]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [46]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [47]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [48]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])